const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const isWatch = process.argv.includes('--watch');

// ---------------------------------------------------------------------------
// Built-in tools registry (global Tools db)
// ---------------------------------------------------------------------------
// skills/registry.js is the canonical ESM source. Extension pages and the
// background SW can't load ES modules, so we bake the registry into a classic
// script that assigns globalThis.AA_TOOLS.
const TOOLS_REGISTRY_OUT = 'extension/lib/tools-registry.js';

async function buildToolsRegistry() {
  const { skillRegistry, settingsMeta } = await import('./skills/registry.js');
  const out = `// GENERATED by build.js from skills/registry.js — do not edit by hand.
// Loaded by background.js (importScripts) and extension pages (script tag).
globalThis.AA_TOOLS = {
  version: 1,
  list: ${JSON.stringify(skillRegistry, null, 2)},
  settingsMeta: ${JSON.stringify(settingsMeta, null, 2)},
  // One prompt-ready line per setting: "key (type...): description".
  settingsVocabularyLines() {
    return Object.entries(this.settingsMeta).map(([k, m]) => {
      let t = m.type;
      if (m.type === 'number' && m.range) t = \`number \${m.range[0]}-\${m.range[1]}\`;
      if (m.type === 'enum' && m.options) t = 'string: ' + m.options.map(o => '"' + o + '"').join(', ');
      return \`- \${k} (\${t}): \${m.description}\`;
    });
  },
  byId(id) { return this.list.find(s => s.id === id) || null; },
  byArea(area) { return this.list.filter(s => s.supportAreas.includes(area)); },
  // chrome.storage.sync settings activated by enabling each of \`ids\`.
  settingsFor(ids) {
    const merged = {};
    for (const id of ids || []) {
      const t = this.byId(id);
      if (t && t.settings) Object.assign(merged, t.settings);
    }
    return merged;
  },
  forPrompt() {
    return this.list.map(s => ({
      id: s.id, name: s.name, description: s.description,
      supportAreas: s.supportAreas, siteRelevance: s.siteRelevance,
    }));
  },
};
`;
  const outPath = path.resolve(__dirname, TOOLS_REGISTRY_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`tools-registry.js: ${skillRegistry.length} built-in tools`);
}

// ---------------------------------------------------------------------------
// Skill core (the toolkit's skill + skill-builder modules)
// ---------------------------------------------------------------------------
// The adaptive-agent layer (SKILL.md parse/validate/resolve/match + the
// Engineer's buildSkill) comes from the ai-for-accessibility-toolkit package
// (a file: dependency on the sibling checkout — toolkit code never lives in
// this tree). Bundled to a classic script assigning globalThis.AA_SKILL_CORE
// so the background SW (importScripts) and extension pages can load it.
const SKILL_CORE_OUT = 'extension/lib/skill-core.js';
const SKILL_CORE_ENTRY = `
export { parseSkill, serializeSkill, validateSkill, resolveSkill, matchSkill, matchSkillToNeed }
  from 'ai-for-accessibility-toolkit/toolkit/core/skill.js';
export { buildSkill, buildSkillPrompt, parseBuiltSkill }
  from 'ai-for-accessibility-toolkit/toolkit/core/skill-builder.js';
`;

async function buildSkillCore() {
  await esbuild.build({
    stdin: { contents: SKILL_CORE_ENTRY, resolveDir: __dirname, loader: 'js' },
    bundle: true,
    format: 'iife',
    globalName: 'AA_SKILL_CORE',
    banner: { js: '// GENERATED by build.js from the ai-for-accessibility-toolkit package — do not edit by hand.' },
    outfile: path.resolve(__dirname, SKILL_CORE_OUT),
    target: 'chrome110',
  });
  console.log('skill-core.js: AA_SKILL_CORE bundled from ai-for-accessibility-toolkit');
}

// ---------------------------------------------------------------------------
// Base ability profiles (blind, deaf, dyslexia, …) from the toolkit
// ---------------------------------------------------------------------------
// Profile data + the merge logic, bundled the same no-copy way as skill-core:
// globalThis.AA_PROFILES = { profiles, mergeProfileTools }.
const PROFILES_OUT = 'extension/lib/profiles.js';
const PROFILES_ENTRY = `
export { profiles, mergeProfileTools }
  from 'ai-for-accessibility-toolkit/tools/profiles/settings.js';
`;

async function buildProfiles() {
  await esbuild.build({
    stdin: { contents: PROFILES_ENTRY, resolveDir: __dirname, loader: 'js' },
    bundle: true,
    format: 'iife',
    globalName: 'AA_PROFILES',
    banner: { js: '// GENERATED by build.js from the ai-for-accessibility-toolkit package — do not edit by hand.' },
    outfile: path.resolve(__dirname, PROFILES_OUT),
    target: 'chrome110',
  });
  console.log('profiles.js: AA_PROFILES bundled from ai-for-accessibility-toolkit');
}

// ---------------------------------------------------------------------------
// Built-in SKILL.md playbooks (global Skills db)
// ---------------------------------------------------------------------------
// Raw markdown baked in verbatim; parsed at boot with AA_SKILL_CORE.parseSkill
// so parsing stays single-sourced in the toolkit.
const SKILL_DOCS_OUT = 'extension/lib/skill-docs.js';

function buildSkillDocs() {
  const dir = path.join(
    path.dirname(require.resolve('ai-for-accessibility-toolkit/package.json')),
    'toolkit/skills/builtin');
  const docs = {};
  for (const f of fs.readdirSync(dir).filter((f) => f.endsWith('.md')).sort()) {
    docs[f] = fs.readFileSync(path.join(dir, f), 'utf8');
  }
  const out = `// GENERATED by build.js from the ai-for-accessibility-toolkit package — do not edit by hand.
// Raw built-in SKILL.md playbooks; parse with AA_SKILL_CORE.parseSkill.
globalThis.AA_SKILL_DOCS_RAW = ${JSON.stringify(docs, null, 2)};
`;
  fs.writeFileSync(path.resolve(__dirname, SKILL_DOCS_OUT), out);
  console.log(`skill-docs.js: ${Object.keys(docs).length} built-in SKILL.md playbooks`);
}

const contentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/content/content.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/content/content.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: true,
  logLevel: 'info',
};

async function build() {
  await buildToolsRegistry();
  await buildSkillCore();
  await buildProfiles();
  buildSkillDocs();
  if (isWatch) {
    const ctx = await esbuild.context(contentConfig);
    await ctx.watch();
    console.log('Watching for changes...');
  } else {
    await esbuild.build(contentConfig);
    console.log('Build complete.');
  }
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
