const esbuild = require('esbuild');
const path = require('path');
const fs = require('fs');

const isWatch = process.argv.includes('--watch');

// ---------------------------------------------------------------------------
// Built-in tools registry (global Tools db)
// ---------------------------------------------------------------------------
// skills/registry.js is the canonical ESM source. Extension pages and the
// background SW can't load ES modules, so we bake the registry into a classic
// script that assigns globalThis.AA_TOOLS.
const TOOLS_REGISTRY_OUT = 'extension/lib/tools-registry.js';

async function buildToolsRegistry() {
  const { skillRegistry, settingsMeta } = await import('./skills/registry.js');
  const out = `// GENERATED by build.js from skills/registry.js — do not edit by hand.
// Loaded by background.js (importScripts) and extension pages (script tag).
globalThis.AA_TOOLS = {
  version: 1,
  list: ${JSON.stringify(skillRegistry, null, 2)},
  settingsMeta: ${JSON.stringify(settingsMeta, null, 2)},
  // One prompt-ready line per setting: "key (type...): description".
  settingsVocabularyLines() {
    return Object.entries(this.settingsMeta).map(([k, m]) => {
      let t = m.type;
      if (m.type === 'number' && m.range) t = \`number \${m.range[0]}-\${m.range[1]}\`;
      if (m.type === 'enum' && m.options) t = 'string: ' + m.options.map(o => '"' + o + '"').join(', ');
      return \`- \${k} (\${t}): \${m.description}\`;
    });
  },
  byId(id) { return this.list.find(s => s.id === id) || null; },
  byArea(area) { return this.list.filter(s => s.supportAreas.includes(area)); },
  // chrome.storage.sync settings activated by enabling each of \`ids\`.
  settingsFor(ids) {
    const merged = {};
    for (const id of ids || []) {
      const t = this.byId(id);
      if (t && t.settings) Object.assign(merged, t.settings);
    }
    return merged;
  },
  forPrompt() {
    return this.list.map(s => ({
      id: s.id, name: s.name, description: s.description,
      supportAreas: s.supportAreas, siteRelevance: s.siteRelevance,
    }));
  },
};
`;
  const outPath = path.resolve(__dirname, TOOLS_REGISTRY_OUT);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, out);
  console.log(`tools-registry.js: ${skillRegistry.length} built-in tools`);
}

const contentConfig = {
  entryPoints: [path.resolve(__dirname, 'extension/content/content.js')],
  bundle: true,
  outfile: path.resolve(__dirname, 'extension/content/content.bundle.js'),
  format: 'iife',
  target: 'chrome110',
  sourcemap: true,
  logLevel: 'info',
};

async function build() {
  await buildToolsRegistry();
  if (isWatch) {
    const ctx = await esbuild.context(contentConfig);
    await ctx.watch();
    console.log('Watching for changes...');
  } else {
    await esbuild.build(contentConfig);
    console.log('Build complete.');
  }
}

build().catch((e) => {
  console.error(e);
  process.exit(1);
});
